### PR TITLE
extract strings from application to en.yml

### PR DESCRIPTION
**Pull request by anule**

### CODE REVIEW

**Comment by anule** [comment]
@bensheldon right now this has all the strings from the application. Do you think I should include the admin panel as well?

**Comment by bensheldon** [comment]
@anule that is a very good question. I think we might want to translate everything just because some screens may move from admin <--> application as this develops.

**Review by bensheldon — APPROVED** [review]
This looks good.

Is it possible to use the relative i18n keys? e.g. within `aid_applications/edits/edit.html.erb` a string is referenced using `I18n.t('.about_program.title')`

**Comment by anule** [comment]
@bensheldon I'll grab the admin strings, then. I want to get this merged before I start on the next ticket.  ~I wasn't able to get the relative strings working, probably because of the nesting in the yml file. Which, I'm not tied to, but I find it makes the yml file more legible. I think as the application splits up in to multiple pages, we can nest them properly and the relative strings will work~ It wasn't working because I had misspelled 'application' 🙃

**Pull request merged**
